import type { Metadata } from "next";
import { Libre_Caslon_Text, Poppins } from "next/font/google";
import "./globals.css";

// Configure Fonts
const libreCaslon = Libre_Caslon_Text({ 
  subsets: ["latin"], 
  weight: ["400", "700"],
  variable: "--font-libre" 
});

const poppins = Poppins({ 
  subsets: ["latin"], 
  weight: ["300", "400", "600"],
  variable: "--font-poppins" 
});

export const metadata: Metadata = {
  title: "STREET EATS |  A Lite Food Truck",
  description: "A dynamic food truck for all your culinary adventures.",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={`${libreCaslon.variable} ${poppins.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}


// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }

